apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhr
spec:
  type: team
  children: []
  members:
    - guest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rhr
spec:
  owner: group:default/rhr
