apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: soxl
  description: soxl - StatelessServiceWithBucket
  annotations:
    backstage.io/source-location: url:https://github.com/patel0ankur/fleet-gitops/blob/main/projects/soxl/deployments/soxl.yaml
    backstage.io/kubernetes-id: soxl
spec:
  type: service
  lifecycle: production
  owner: group:default/soxl
  system: system:default/soxl
