apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: final-demo
  description: final-demo - StatelessServiceWithBucket
  annotations:
    backstage.io/source-location: url:https://github.com/patel0ankur/fleet-gitops/blob/main/projects/demo-team/deployments/final-demo.yaml
    backstage.io/kubernetes-id: final-demo
spec:
  type: service
  lifecycle: production
  owner: group:default/demo-team
  system: system:default/demo-team
