apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: final-demo
  description: final-demo - StatelessServiceWithBucket (scaffolded by Fleet Backstage)
  annotations:
    backstage.io/source-location: url:https://github.com/patel0ankur/fleet-gitops/blob/main/projects/demo-team/deployments/final-demo.yaml
  labels:
    fleet.platform/kro-instance: final-demo
spec:
  type: service
  lifecycle: production
  owner: demo-team
  system: demo-team
